dog_breed_names = {"affenpinscher": "Affenpinscher",
"african": "African",
"airedale": "Airedale",
"akita": "Akita",
"appenzeller": "Appenzeller",
"basenji": "Basenji",
"beagle": "Beagle",
"bluetick": "Bluetick",
"borzoi": "Borzoi",
"bouvier": "Bouvier",
"boxer": "Boxer",
"brabancon": "Brabancon",
"briard": "Briard",
"bulldog-boston": "Boston Bulldog",
"bulldog-english": "English Bulldog",
"bulldog-french": "French Bulldog",
"bullterrier-staffordshire": "Staffordshire Bullterrier",
"cairn": "Cairn",
"cattledog-australian": "Australian Cattledog",
"chihuahua": "Chihuahua",
"chow": "Chow",
"clumber": "Clumber",
"cockapoo": "Cockapoo",
"collie-border": "Border Collie",
"coonhound": "Coonhound",
"corgi-cardigan": "Cardigan Corgi",
"cotondetulear": "Cotondetulear",
"dachshund": "Dachshund",
"dalmatian": "Dalmatian",
"dane-great": "Great Dane",
"deerhound-scottish": "Scottish Deerhound",
"dhole": "Dhole",
"dingo": "Dingo",
"doberman": "Doberman",
"elkhound-norwegian": "Norwegian Elkhound",
"entlebucher": "Entlebucher",
"eskimo": "Eskimo",
"frise-bichon": "Bichon Frise",
"germanshepherd": "German Shepherd",
"greyhound-italian": "Italian Greyhound",
"groenendael": "Groenendael",
"hound-afghan": "Afghan Hound",
"hound-basset": "Basset Hound",
"hound-blood": "Blood Hound",
"hound-english": "English Hound",
"hound-ibizan": "Ibizan Hound",
"hound-walker": "Walker Hound",
"husky": "Husky",
"keeshond": "Keeshond",
"kelpie": "Kelpie",
"komondor": "Komondor",
"kuvasz": "Kuvasz",
"labrador": "Labrador",
"leonberg": "Leonberg",
"lhasa": "Lhasa",
"malamute": "Malamute",
"malinois": "Malinois",
"maltese": "Maltese",
"mastiff-bull": "Bull Mastiff",
"mastiff-english": "English Mastiff",
"mastiff-tibetan": "Tibetan Mastiff",
"mexicanhairless": "Mexican Hairless",
"mix": "Mix",
"mountain-bernese": "Bernese Mountain",
"mountain-swiss": "Swiss Mountain",
"newfoundland": "Newfoundland",
"otterhound": "Otterhound",
"papillon": "Papillon",
"pekinese": "Pekinese",
"pembroke": "Pembroke",
"pinscher-miniature": "Miniature Pinscher",
"pointer-german": "German Pointer",
"pointer-germanlonghair": "German Longhair Pointer",
"pomeranian": "Pomeranian",
"poodle-miniature": "Miniature Poodle",
"poodle-standard": "Standard Poodle",
"poodle-toy": "Toy Poodle",
"pug": "Pug",
"puggle": "Puggle",
"pyrenees": "Pyrenees",
"redbone": "Redbone",
"retriever-chesapeake": "Chesapeake Retriever",
"retriever-curly": "Curly Retriever",
"retriever-flatcoated": "Flatcoated Retriever",
"retriever-golden": "Golden Retriever",
"ridgeback-rhodesian": "Rhodesian Ridgeback",
"rottweiler": "Rottweiler",
"saluki": "Saluki",
"samoyed": "Samoyed",
"schipperke": "Schipperke",
"schnauzer-giant": "Giant Schnauzer",
"schnauzer-miniature": "Miniature Schnauzer",
"setter-english": "English Setter",
"setter-gordon": "Gordon Setter",
"setter-irish": "Irish Setter",
"sheepdog-english": "English Sheepdog",
"sheepdog-shetland": "Shetland Sheepdog",
"shiba": "Shiba",
"shihtzu": "Shihtzu",
"spaniel-blenheim": "Blenheim Spaniel",
"spaniel-brittany": "Brittany Spaniel",
"spaniel-cocker": "Cocker Spaniel",
"spaniel-irish": "Irish Spaniel",
"spaniel-japanese": "Japanese Spaniel",
"spaniel-sussex": "Sussex Spaniel",
"spaniel-welsh": "Welsh Spaniel",
"springer-english": "English Springer",
"stbernard": "St. Bernard",
"terrier-american": "American Terrier",
"terrier-australian": "Australian Terrier",
"terrier-bedlington": "Bedlington Terrier",
"terrier-border": "Border Terrier",
"terrier-dandie": "Dandie Terrier",
"terrier-fox": "Fox Terrier",
"terrier-irish": "Irish Terrier",
"terrier-kerryblue": "Kerryblue Terrier",
"terrier-lakeland": "Lakeland Terrier",
"terrier-norfolk": "Norfolk Terrier",
"terrier-norwich": "Norwich Terrier",
"terrier-patterdale": "Patterdale Terrier",
"terrier-russell": "Russell Terrier",
"terrier-scottish": "Scottish Terrier",
"terrier-sealyham": "Sealyham Terrier",
"terrier-silky": "Silky Terrier",
"terrier-tibetan": "Tibetan Terrier",
"terrier-toy": "Toy Terrier",
"terrier-westhighland": "Westhighland Terrier",
"terrier-wheaten": "Wheaten Terrier",
"terrier-yorkshire": "Yorkshire Terrier",
"vizsla": "Vizsla",
"weimaraner": "Weimaraner",
"whippet": "Whippet",
"wolfhound-irish": "Irish Wolfhound"
}

def prettify_dog_breed(dog_breed):
  return dog_breed_names[dog_breed]